name: ci

on:
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: deps
        run: npm ci

      # No tests yet
      # - name: tests
      #   run: npm run test

      - name: eslint
        run: npm run lint

      - name: prettier
        run: npm run format
