name: release

on:
  release:
    types: [created]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to registry
        uses: docker/login-action@v1
        with:
          registry: ${{ secrets.DOCKER_REGISTRY }}
          username: ${{ secrets.DOCKER_REGISTRY_USER }}
          password: ${{ secrets.DOCKER_REGISTRY_PASS }}

      - name: Tag name
        id: tag_name
        run: echo ::set-output name=TAG_NAME::${GITHUB_REF/refs\/tags\//}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            ${{ secrets.DOCKER_REGISTRY }}/vagahbond/uni-verse/frontend
            ${{ secrets.DOCKER_REGISTRY }}/vagahbond/uni-verse/frontend:${{ steps.tag_name.outputs.TAG_NAME }}
        env:
          NEXT_PUBLIC_MINIO_URL: https://minio.vagahbond.com
          NEXT_PUBLIC_MAX_IMAGE_SIZE: 3000000
          NEXT_PUBLIC_MAX_FILE_SIZE: 10000000
          NEXT_PUBLIC_API_URL: https://uni-verse.api.vagahbond.com
          NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY: $NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY
          NEXT_PUBLIC_UNIVERSE_PRIVATE_KEY: $NEXT_PUBLIC_UNIVERSE_PRIVATE_KEY
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
